"""initial schema

Revision ID: 85ea531eb367
Revises: 
Create Date: 2026-09-26 03:12:53.947551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ea531eb367'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candles_asset_class'), 'candles', ['asset_class'], unique=False)
    op.create_index(op.f('ix_candles_symbol'), 'candles', ['symbol'], unique=False)
    op.create_index('ix_candles_symbol_ts', 'candles', ['asset_class', 'symbol', 'timestamp'], unique=False)
    op.create_table('kill_switch_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('engaged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_switch_audit_logs_engaged_at'), 'kill_switch_audit_logs', ['engaged_at'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_order_id', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('trading_mode', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=True)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entry_rule', sa.JSON(), nullable=False),
    sa.Column('exit_rule', sa.JSON(), nullable=False),
    sa.Column('max_position_size', sa.Float(), nullable=False),
    sa.Column('stop_loss_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_symbol'), 'strategies', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategies_symbol'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_kill_switch_audit_logs_engaged_at'), table_name='kill_switch_audit_logs')
    op.drop_table('kill_switch_audit_logs')
    op.drop_index('ix_candles_symbol_ts', table_name='candles')
    op.drop_index(op.f('ix_candles_symbol'), table_name='candles')
    op.drop_index(op.f('ix_candles_asset_class'), table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
